name: Hello World
on: workflow_dispatch
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-ghatest-org-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - run: echo "Hello World"
