name: Hello World - Enterprise
on: workflow_dispatch
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-ghatest-ent-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - run: echo "Hello World"
