name: Hello World - Enterprise
on: workflow_dispatch
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-ghatest-ent-p-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
